#!/usr/bin/env bash
USER='jcottobboni'
NAME='Joao Carlos Ottobboni'
EMAIL='jcottobboni@gmail.com'

PROJECTS='${HOME}/projects'
GITHUB='${HOME}/projects/github.com'
GITLAB='${HOME}/projects/gitlab.com'
BITBUCKET='${HOME}/projects/bitbucket.org'
DOCKERFILES='${HOME}/projects/gitlab.com/dockerfiles'
TERRAFORM='${HOME}/projects/gitlab.com/tf_modules'
PLAYBOOKS='${HOME}/projects/playbooks'
CHEF_ROLES='${HOME}/projects/gitlab.com/chef/roles'
CHEF_ENVIRONMENTS='${HOME}/projects/gitlab.com/chef/environments'
CHEF_HANDLERS='${HOME}/projects/gitlab.com/chef/handlers'
CHEF_DATA_BAGS='${HOME}/projects/gitlab.com/chef-data-bags'
CHEF_COOKBOOKS='${HOME}/projects/gitlab.com/chef-cookbooks'
DCOS_CLUSTERS='${HOME}/projects/gitlab.com/clusters/dcos-clusters'
