FILES_TO_INSTALL=(
	.config/i3/config
	.config/i3/lock.sh
	.config/polybar/config
	.config/polybar/launch.sh
	.config/terminator/config
	.config/gtk-3.0/settings.ini
	compton.conf
	.zshrc
	.xsessionrc
	.Xresources
	.aliases
	.exports
	.config/rofi/onedark.rasi
	.config/nvim/init.vim
	.gitconfig
	.gitignore_global
	.gitignore
)
